{% set name = "ptxcompiler" %}
{% set version = "0.7.0" %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.8").split(".")[0] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rapidsai/ptxcompiler/archive/refs/tags/{{ version }}.tar.gz
  sha256: f7e44e43b3d7264d1cfb9cb03ce7b792bfc6a1d4647dc956292c8a2a1c090e9f

build:
  number: 3
  skip: true  # [(not linux) or cuda_compiler_version in (undefined, "None")]
  ignore_run_exports_from:
    - {{ compiler("cuda") }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}
  host:
    - python
    - pip
    - cudatoolkit {{ cuda_compiler_version }}
  run:
    - python
    - cudatoolkit >={{ cuda_major ~ ".0" }},<={{ cuda_compiler_version }}
  run_constrained:
    - __cuda >={{ cuda_major ~ ".0" }}
    - numba >=0.54

test:
  imports:
    - ptxcompiler

about:
  home: https://github.com/rapidsai/ptxcompiler
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PTX Static compiler and Numba patch

extra:
  recipe-maintainers:
    - gmarkall
    - prashantkhoje
    - bdice
    - jakirkham
